[tool.poetry]
name = "aws-cloudwatch-log-group"
version = "0.0.1"
description = "Pulling AWS CloudWatch Log Groups"
authors = ["James Hogkinson <james@terminaloutcomes.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.21.30"

[tool.poetry.dev-dependencies]
pylint = "^2.13.3"
mypy = "^0.942"
black = "^22.3.0"
pytest = "^7.1.1"
boto3-stubs = {extras = ["logs"], version = "^1.21.30"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
