[tool.poetry]
name = "aws-cloudwatch-log-group"
version = "0.0.2"
description = "Pulling AWS CloudWatch Log Groups"
authors = ["James Hogkinson <james@terminaloutcomes.com>"]
license = "MIT"
include = [
    "CHANGELOG.md"
]

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.24.17"
mypy-boto3-logs = "^1.24.0"

[tool.poetry.dev-dependencies]
pylint = "^2.14.3"
mypy = "^0.961"
black = "^22.3.0"
pytest = "^7.1.2"
boto3-stubs = {extras = ["logs"], version = "^1.24.16"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.MASTER]
max-line-length=200

[tool.poetry.scripts]
aws-cloudwatch-log-group = "aws_cloudwatch_log_group.__main__:main"
