[tool.poetry]
name = "aws-cloudwatch-log-group"
version = "0.0.3"
description = "Pulling AWS CloudWatch Log Groups"
authors = ["James Hogkinson <james@terminaloutcomes.com>"]
license = "MIT"
include = [
    "CHANGELOG.md"
]

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.25.3"
mypy-boto3-logs = "^1.24.36"

[tool.poetry.dev-dependencies]
pylint = "^2.15.4"
mypy = "^0.982"
black = "^22.10.0"
pytest = "^7.1.3"
boto3-stubs = {extras = ["logs"], version = "^1.24.95"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.MASTER]
max-line-length=200

[tool.poetry.scripts]
aws-cloudwatch-log-group = "aws_cloudwatch_log_group.__main__:main"
